# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_hadamardKernel')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_hadamardKernel')
    _hadamardKernel = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_hadamardKernel', [dirname(__file__)])
        except ImportError:
            import _hadamardKernel
            return _hadamardKernel
        try:
            _mod = imp.load_module('_hadamardKernel', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _hadamardKernel = swig_import_helper()
    del swig_import_helper
else:
    import _hadamardKernel
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def PAL_kernel(N, n, t):
    return _hadamardKernel.PAL_kernel(N, n, t)
PAL_kernel = _hadamardKernel.PAL_kernel

def WAL_kernel(N, n, t):
    return _hadamardKernel.WAL_kernel(N, n, t)
WAL_kernel = _hadamardKernel.WAL_kernel

def fwhtKernelSequency(*args):
    return _hadamardKernel.fwhtKernelSequency(*args)
fwhtKernelSequency = _hadamardKernel.fwhtKernelSequency

def fwhtKernelOrdinary(*args):
    return _hadamardKernel.fwhtKernelOrdinary(*args)
fwhtKernelOrdinary = _hadamardKernel.fwhtKernelOrdinary

def fwhtKernelPaley(*args):
    return _hadamardKernel.fwhtKernelPaley(*args)
fwhtKernelPaley = _hadamardKernel.fwhtKernelPaley

def fwhtKernel2dSequency(*args):
    return _hadamardKernel.fwhtKernel2dSequency(*args)
fwhtKernel2dSequency = _hadamardKernel.fwhtKernel2dSequency

def fwhtKernel2dOrdinary(*args):
    return _hadamardKernel.fwhtKernel2dOrdinary(*args)
fwhtKernel2dOrdinary = _hadamardKernel.fwhtKernel2dOrdinary

def fwhtKernel2dPaley(*args):
    return _hadamardKernel.fwhtKernel2dPaley(*args)
fwhtKernel2dPaley = _hadamardKernel.fwhtKernel2dPaley
# This file is compatible with both classic and new-style classes.


